version: '3.0'

services:
  server:
    container_name: nest
    build:
      dockerfile: ./Dockerfile.dev
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - .development.env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
